version: "3"

# docker run --privileged -dit --name kacpp-mail --net kaawsnet -p 25:25 -p 465:465 -p 587:587 -v /home:/home/mail_users -v /home/local_etc:/usr/local/etc kagalpandh/kacpp-mail

services:
    kacpp-mail:
        image: kagalpandh/kacpp-imap
        container_name: kacpp-imap
        volumes:
            - /home/local_etc:/usr/local/etc
            - /home:/home/mail_users
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            - kaawsnet
        ports:
            - "993:993"
            - "995:995"
        cap_add:
            - SYS_ADMIN
        privileged: true
        restart: always
        env_file: kacpp-imap.src
#         environment:
#             PGDATA: /home/data/db/pgdata
networks:
    kaawsnet:
        external: true


